config/routes.rb
  require 'will_paginate/array'
CashHoppers::Application.routes.draw do

  get "settings/get"

  get "settings/set"

  root :to => 'pages#home'
  get 'pages/hoppers_activity'
  get 'pages/business_level'
  get 'pages/terms'
  get 'pages/trade_show'
  get 'users/index'
  get 'pages/faq'

  namespace :admin do
    resources :asks

    get 'pages/index', :as => 'index'


    post "users/change_user_role"
    get "users/tasks_photo"
    get "users/index"
    post "users/unsubscribe_user"
    delete'users/delete_user/:id',              to:  'users#delete_user'

    resources :applications

    #hops
    resources :hops, only: [:create]
    get 'regular_hops',                    to: 'hops#regular'
    get 'daily_hops',                      to: 'hops#daily'
    get 'current_hops',                    to: 'hops#current'
    get 'archived_hops',                   to: 'hops#archived'
    get 'hop/:id',                         to: 'hops#show',              as: 'hop'
    get 'hops/new_regular',                to: 'hops#new_regular',       as: 'new_regular_hop'
    get 'hops/new_daily',                  to: 'hops#new_daily',         as: 'new_daily_hop'
    get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
    get 'hop/:id/edit_daily',              to: 'hops#edit_daily',        as: 'edit_daily_hop'
    delete 'hop/:id',                      to: 'hops#destroy',           as: 'hop'
    put 'hop/:id',                         to: 'hops#update',            as: 'hop'
    post 'close_hop/:id',                  to: 'hops#close',             as: 'close_hop'
    post 'hops/print_hop_to_pdf',          to: 'hops#print_hop_to_pdf',      as: 'print_hop_to_pdf'
    post 'hops/print_hop_list_to_pdf',     to: 'hops#print_hop_list_to_pdf',      as: 'print_hop_list_to_pdf'
    post 'hops/import_from_excel',         to: 'hops#import_from_excel',      as: 'import_from_excel'
    post 'hops/print_hop_to_excel',        to: 'hops#print_hop_to_excel',      as: 'print_hop_to_excel'
    post 'hops/print_hops_to_excel',       to: 'hops#print_hops_to_excel',      as: 'print_hops_to_excel'
    get 'hops/render_hoppers',            to: 'hops#render_hoppers',           as: 'render_hoppers'
    get 'hops/hop_photos',                to: 'hops#hop_photos',               as: 'hop_photos'
    get 'hops/export_photos_zip',         to: 'hops#export_photos_zip',        as: 'export_photos_zip'
    get 'hops/edit_photo',                to: 'hops#edit_photo',               as: 'edit_photo'
    post 'hops/delete_photo',                to: 'hops#delete_photo',           as: 'delete_photo'

    #hop_tasks
    resources :hop_tasks

    #prizes
    resources :prizes

    post 'prizes/random_user' ,             to: 'prizes#random_user' , as: 'random_user'
    post 'prizes/accept_user' ,             to: 'prizes#accept_user' , as: 'accept_user'
    #ads
    resources :ads

    match "hoppers/find_hopper"
    match "hoppers/hopper_list"
    match '/hoppers/search_hoppers' => "hoppers#search_hoppers"
    get '/hoppers/search_user'
    get '/hoppers/search_hop_list'
    get '/hoppers/search_zip_list'

    post '/hoppers/select_user'
    post '/hoppers/select_hop'
    post '/hoppers/select_zip'
    post '/hoppers/list_by_zip'
    post '/hoppers/list_by_hop'
    post '/hoppers/search_by_name' => 'hoppers#search_by_name'
    post '/hoppers/search_by_zip' => 'hoppers#search_by_zip'
    post '/hoppers/search_by_hop' => 'hoppers#search_by_hop'
    post '/hoppers/hopper_to_pdf' => 'hoppers#hopper_to_pdf'
    post '/hoppers/winners_to_pdf' => 'hoppers#winners_to_pdf'
    get '/hoppers/export_to_excel' => 'hoppers#export_to_excel'
    get '/hoppers/winners_to_excel' => 'hoppers#winners_to_excel'
    post '/hoppers/select_all' => 'hoppers#select_all'
    get '/hoppers/winners_list' => 'hoppers#winners_list'

    #messages
    get 'messages/email_tool'
    get 'messages/message_tool'
    post 'messages/message_create'
    post 'messages/email_create'
    get 'messages/hops_list'
    get 'messages/users_list'
    get 'messages/email_history'
    get 'messages/message_history'
    delete 'messages/destroy_message'
    post 'messages/get_user_list'


  end

  namespace :api do
    #session
    post 'sessions',                       to: 'sessions#create',        as: 'login'
    post 'sign_up',                        to: 'sessions#sign_up',       as: 'sign_up'
    delete 'sessions',                     to: 'sessions#destroy',       as: 'logout'
    post 'confirm_registration',           to: 'sessions#confirm_registration'
    post 'sign_in_via_service',            to: 'sessions#sign_in_via_service'
    get 'sessions/service_exist',          to: 'sessions#service_exist'
    post 'sessions/set_android_registration_id', to: 'sessions#set_android_registration_id'
    post 'sessions/reset_password',        to: 'sessions#reset_password'

    get 'ads/get_ads' => 'ads#index'

    #hops
    get 'hops/regular',                    to: 'hops#regular'
    get 'hops/daily',                      to: 'hops#daily'
    post 'hops/assign',                    to: 'hops#assign'
    get 'hop/get_tasks',                   to: 'hops#get_tasks'
    get 'hop/get_hop',                     to: 'hops#get_hop_by_id'
    get 'hop/score',                       to: 'hops#score'
    get 'hops/yesterdays_winner',          to: 'hops#yesterdays_winner'
    get 'hop/prizes',                      to: 'hops#prizes'
    post 'hop/disable_password',            to: 'hops#disable_password'
    get 'task/get_hop_task',               to: 'user_hop_tasks#get_hop_task_by_id'
    post 'payment/buy_hop',                to: 'payment#buy_hop'

    #users hop tasks
    post 'task/submit',                    to: 'user_hop_tasks#create'
    get 'tasks/get_friends_hop_tasks',     to: 'user_hop_tasks#friends_hop_tasks'
    get 'tasks/get_all_hoppers_hop_tasks', to: 'user_hop_tasks#all_hoppers_hop_tasks'
    post 'task/like',                      to: 'user_hop_tasks#like'
    get 'task/likes_count',                to: 'user_hop_tasks#likes_count'
    post 'task/comment',                   to: 'user_hop_tasks#comment'
    get 'task/get_comments',               to: 'user_hop_tasks#comments'
    post 'task/notify_by_share',           to: 'user_hop_tasks#notify_by_share'
    get 'task/get_user_hop_task_by_id',    to: 'user_hop_tasks#get_user_hop_task_by_id'

    #friends
    get 'friends/get_friends',             to: 'friends#get_friends'
    get 'friends/get_requested_friends',   to: 'friends#get_requested_friends'
    get 'friends/get_pending_friends',     to: 'friends#get_pending_friends'
    post 'friends/send_request',           to: 'friends#send_request'
    post 'friends/accept_request',         to: 'friends#accept_request'
    post 'friends/decline_request',        to: 'friends#decline_request'
    post 'friends/cancel_request',         to: 'friends#cancel_request'
    post 'friends/delete_friend',          to: 'friends#delete_friend'

    #messages
    post 'messages/send_message',          to: 'messages#send_message_to_friends'
    get 'messages/synchronize',            to: 'messages#synchronize_messages'
    get 'messages/thread',                 to: 'messages#get_users_messages_thread'
    get 'messages/history',                to: 'messages#messages_history'
    delete 'messages/remove_message',      to: 'messages#remove_message'

    #users

    get "users/index"
    get 'users/get_users',                 to: 'users#index'
    get 'users/get_my_info',               to: 'users#get_my_info'
    get 'users/get_user_info',             to: 'users#get_user_info'
    post 'users/update_profile',           to: 'users#update_profile'

    #events
    get 'notifications',                   to: 'notifications#get_events_list'

    #settings
    post 'settings/set',                   to: 'settings#set'
    get 'settings/get',                    to: 'settings#get'

    #payment
    get 'payment/get_frog_legs_count',     to: 'payment#get_frog_legs_count'
    post 'payment/refill_your_account',    to: 'payment#refill_your_account'
    post 'payment/disable_ads',            to: 'payment#disable_ads'

  end

  devise_for :users, :controllers => {:sessions =>'CustomDevise::Sessions'}

  get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
  get 'user/:id',                        to: 'users#profile',          as: 'user'


  match '/auth/:service/callback' => 'services#add_zip'
  get 'services/add_zip', :to => 'services#add_zip'
 
  resources :services, :only => [:index, :create, :destroy]
  resources :ad_types

  get 'friends', to: 'friends#friends'
  get 'find_friends', to: 'friends#find_friends'
  post 'friends/create_request', to: 'friends#create_request'
  post 'friends/cancel_request', to: 'friends#cancel_request'
  post 'friends/accept_request', to: 'friends#accept_request'
  post 'friends/decline_request', to: 'friends#decline_request'
  post 'friends/delete_friend', to: 'friends#delete_friend'


  get 'messages/friends_list'
  get 'messages/friend_messages'
  post 'messages/synchronize'
  post 'messages/send_message'
  post 'messages/find_friend'

  get '/auth/failure' => 'pages#home'
end

app/controllers/admin/hoppers_controller.rb
class Admin::HoppersController < Admin::AdminController
  include ::PdfWritter


  def find_hopper
    @tab = 'find_hoppers'

    @user = User.find_by_id(session[:last_hopper])  if session[:last_hopper]
  end

  def hopper_list
   @tab = 'generate_hoppers_list'
   @id_array = session[:last_hoppers]  if session[:last_hoppers]
   @users = session[:last_hoppers].map{|id| User.find_by_id(id)}  if session[:last_hoppers]

   if  params[:id]
     output = PdfWritter::TestDocument.new.to_pdf_hopper_list(params[:id])
     respond_to do |format|
       format.pdf {
         send_data output, :filename => "HopperList.pdf", :type => "application/pdf", :disposition => "inline"
       }
     end
   end
  end

  def sub_layout
    'admin/hoppers_tabs'
  end

  def search_by_name
    conditions = ["(user_name LIKE ? OR user_name LIKE ? ) AND deleted not 1", "%#{params[:qwery]}%", "%#{params[:query1]}%"]
    @users = User.paginate(page: params[:page], per_page:9, conditions:  conditions)
    render :partial=> 'users_list'
  end

  def search_user
    params[:page] ||= 1
    params[:per_page] ||= 7
    @users = User.paginate page: params[:page], per_page: params[:per_page], conditions: {:deleted=> !true}
    render :partial=> 'users_list'
  end

  def search_hop_list
    params[:page] ||= 1
    params[:per_page] ||= 7
    @hops = Hop.paginate page: params[:page], per_page: params[:per_page]
     render partial: 'users_hop_list'
  end

  def search_zip_list
    params[:page] ||= 1
    params[:per_page] ||= 7
    @zips = User.group(:zip).select(:zip).paginate page: params[:page], per_page: params[:per_page], conditions: {:deleted=> !true}
     render partial: 'users_zip_list'
  end

  def select_user
    @user = User.find_by_id(params[:id])
    session[:last_hopper]= params[:id]
    render :partial => 'hopper_info'

  end

  def select_hop
    @users = Hop.find_by_id(params[:id]).hoppers.where(deleted: !true)

    @id_array = @users.map{|user| user.id }
    #session[:last_hoppers]= @id_array
    render :partial => 'generate_hop_list'
  end

  def select_zip
    @users = User.where(:zip => params[:zip], deleted: !true).all

    @id_array = @users.map{|user| user.id }

    session[:last_hoppers]= @id_array
    render :partial => 'generate_hop_list'
    #render :text => @id_array
  end


  def search_by_zip
    conditions = ["zip LIKE ? OR zip LIKE ?", "%#{params[:qwery]}%", "%#{params[:qwery]}%"]
    @zips = User.group(:zip).select(:zip)
    @zips = @zips.paginate(:page => 1, :per_page => 9,  conditions:  conditions )
    render :partial=> 'users_zip_list'
  end

  def search_by_hop
    conditions = ["name LIKE ? OR name LIKE ?", "%#{params[:qwery]}%", "%#{params[:qwery]}%"]
    @hops = Hop.paginate(page: params[:page], per_page:9, conditions:  conditions)
    render :partial=> 'users_hop_list'
  end

  def hopper_to_pdf
    if  params[:id]
      output = PdfWritter::TestDocument.new.to_pdf_hopper(params[:id])
      respond_to do |format|
        format.pdf {
          send_data output, :filename => "Hopper.pdf", :type => "application/pdf", :disposition => "inline"
        }
      end
    end
  end

  def export_to_excel
    @gamers = []
    for i in params[:id]
      @gamers  << User.find_by_id(i)
    end

    respond_to do |format|
      format.xls{

          clients = Spreadsheet::Workbook.new
          list = clients.create_worksheet :name => 'List of cliets'
          list.row(1).push "Hoppers list"
          list.row(3).concat %w{Id User_name First_name Last_name Zip Email}
          @gamers.each_with_index { |client, i|
            list.row(i+4).push client.id,client.user_name,client.first_name,client.last_name,client.zip,client.email
          }
          header_format = Spreadsheet::Format.new :color =>:green, :size => 10
          list.row(1).default_format = header_format
          #output to blob object
          blob = StringIO.new("")
          clients.write blob
          #respond with blob object as a file
          send_data blob.string, :type => 'xls', :filename =>'Hoppers_list.xls'

      }
    end
  end
  def select_all
    @users = User.where(deleted:  !true)

    @id_array = @users.map{|user| user.id }

    session[:last_hoppers]= @id_array
    render :partial => 'generate_hop_list'


  end

  def winners_list
    @tab = 'winners_list'

    #@winners = Prize.all.map{|prize| prize.user}.compact!
    users=[]
    user = User.where(deleted: !true)
    user.each do |i|
      users<< i.id unless i.prizes.blank?
    end


    @winners_grid = initialize_grid(Prize,
                                  :include => [:user, :hop],
                                  per_page: 20,
                                  conditions: {:accept => true}

    )
  end

  def winners_to_pdf
     output = PdfWritter::TestDocument.new.to_pdf_winner_list(params[:winners])
    respond_to do |format|
      format.pdf {
        send_data output, :filename => "Winner.pdf", :type => "application/pdf", :display=>'inline'
      }
   end

  end

  def winners_to_excel
    winner =[]
    params[:winners].each do |i|
      winner << Prize.find_by_id(i)

    end


    respond_to do |format|
      format.xls{

        clients = Spreadsheet::Workbook.new
        list = clients.create_worksheet :name => 'Winners'
        list.row(1).push "Winners"
        list.row(3).concat ['Winners', 'Place', 'Prize', 'Prize type', 'Hop name']
        winner.each_with_index { |client, i|
          list.row(i+4).push client.user.user_name,client.place,client.cost,client.prize_type,client.hop.name
        }
        header_format = Spreadsheet::Format.new :color =>:green, :size => 10
        list.row(1).default_format = header_format
        #output to blob object
        blob = StringIO.new("")
        clients.write blob
        #respond with blob object as a file
        send_data blob.string, :type => 'xls', :filename =>'Winners_list.xls'

      }
    end
  end


end

app/views/admin/hoppers/_generate_hop_list.html.haml
-if @users.blank?
  %h3.text-center
    No users
-else
  %br
  .row-fluid
    .span12
      %table
        %tr
          %td.span1
            %b User id
          %td.span1
            %b First name
          %td.span1
            %b Last name
          %td.span1
            %b User name
          %td.span1
            %b Email
          %td.span1
            %b ZIP
        - for i in @users
          %tr
            %td.span1
              =i.id
            %td.span1
              = i.first_name
            %td.span1
              = link_to i.last_name, user_path(:id => i.id)

            %td.span1
              =i.user_name
            %td.span1
              =i.email
            %td.span1
              =i.zip
  %br
  .row-fluid
    .span2

      =  link_to "Email to list", admin_messages_email_tool_path({:id=> @id_array}),:class=>"btn btn-success"
      %br
      %br
      = link_to "Messages to list", admin_messages_message_tool_path({:id=> @id_array}) , :class=>"btn btn-success "
    .span10.text-right
      = link_to("Export file to Excel", admin_hoppers_export_to_excel_path(:id => @id_array, :format => 'xls'),  :class=>" btn btn-success" )
      %br
      %br
      = link_to("Export file to PDF",  admin_hoppers_hopper_list_path(:id =>@id_array, :format => 'pdf'),:method => 'post',  :target => '_blank', :class=>"btn btn-success" )

app/views/admin/hoppers/_hopper_info.html.haml
%br
.row-fluid.print
  .span5
    %table
      %tr
        %td
          %b User name
        %td
          = @user.first_name
      %tr
        %td
          %b User id
        %td
          =@user.id
      %tr
        %td
          %b Password
        .td
          = @user.password
      %tr
        %td
          %b Name
        %td
          = @user.user_name
      %tr
        %td
          %b Zip
        %td
          = @user.zip
      %tr
        %td
          %b Email
        %td
          = @user.email
      %tr
        %td
          %b Phone
        %td
          = @user.phone
      %tr
        %td
          %b Facebook id
        %td
          = @user.facebook
      %tr
        %td
          %b Twitter id
        %td
          = @user.twitter
      %tr
        %td
          %b Player since
        %td
          = @user.created_at
    .text-center.non-print
      %br
        = link_to "Send email to user", admin_messages_email_tool_path({:id=>[@user.id]}), :class=>"span9   btn-success span10 non-print"
      %br
        = link_to "Send app massege to user", admin_messages_message_tool_path({:id=>[@user.id]}), :class=>"span9  btn-success non-print"
      %br
        = link_to"send text to user", '#', :class=>"span9   btn-success non-print"

  .span3
    .span12
      = image_tag @user.avatar.url
  .span2
    %table
      .tr
        .td
          %b Hops played
          %br
      -unless @user.games.blank?
        -for i in @user.games
          .tr
            .td
              = i.name
  .span2
    %table
      %tr
        %td
          %b Hops won
          %br
        -unless @user.prizes.blank?
          -for i in @user.games
            %tr
              %td
                = Hop.find_by_id( i.id).name
.row-fluid.non-print
  .span8
  .span4.text-center
    = link_to("Export file to PDF",  admin_hoppers_hopper_to_pdf_path(:id =>@user.id, :format => 'pdf'),:method => 'post',:target => '_blank' , :class=>" span12  btn btn-success non-print" )
%br
.row-fluid.non-print
  .span8
  .span4.text-center
    = link_to("Print user file",'#', :onclick=>"window.print(); return false;", :class=>"span12 btn btn-success non-print" )

app/views/admin/hoppers/_users_hop_list.html.haml
#hops_list
  .row-fluid
    .span7
      = will_paginate @hops, renderer: BootstrapPagination::Rails
    .span5.text-right.row
      = text_field_tag :input, params[:query], class: 'span7', id: 'search_field'
      = link_to 'Search', '', class: 'btn span4', id: 'search_hop'
  %table.table.table-condensed
    %tr
      %th
        Id
      %th
        Name
      %th
    - @hops.each do |hop|
      %tr
        %td
          = hop.id
        %td
          = hop.name

        %td{style: 'text-align: right'}
          %button.btn.btn-mini.btn-success{:onclick => "select('#{admin_hoppers_select_hop_path(:id =>hop.id)}')"}
            Select
  = will_paginate @hops, renderer: BootstrapPagination::Rails

app/views/admin/hoppers/_users_list.haml
.row-fluid
  .span7
    = will_paginate @users, renderer: BootstrapPagination::Rails
  .span5.text-right.row
    = text_field_tag :input, params[:query], class: 'span7', id: 'search_field'
    = link_to 'Search', '', class: 'btn span4', id: 'search_name'
%table.table.table-condensed
  %tr
    %th
      Id
    %th
      user Name
    %th
      first_name
    %th
  - @users.each do |user|
    %tr
      %td
        = user.id
      %td
        = user.user_name
      %td
        = user.first_name

      %td{style: 'text-align: right'}
        %button.btn.btn-mini.btn-success{:onclick => "select('#{admin_hoppers_select_user_path(:id =>user.id)}')"}
          Select
= will_paginate @users, renderer: BootstrapPagination::Rails

app/views/admin/hoppers/_users_zip_list.html.haml
#zips_list
  .row-fluid
    .span7
      = will_paginate @zips, renderer: BootstrapPagination::Rails, inner_window: 0, outer_window: 0
    .span5.text-right.row
      = text_field_tag :input, params[:query], class: 'span7', id: 'search_field'
      = link_to 'Search',  '', class: 'btn span4', id: 'search_zip'
  %table.table.table-condensed
    %tr
      %th
        zip
      %th
    - @zips.each do |zip|
      %tr
        %td
          = zip.zip

        %td{style: 'text-align: right'}
          %button.btn.btn-mini.btn-success{:onclick => "select('#{admin_hoppers_select_zip_path(:zip =>zip.zip)}')"}
            Select
  = will_paginate @zips, renderer: BootstrapPagination::Rails

app/views/admin/hoppers/find_hopper.html.haml
= render partial: 'layouts/modal_crud'
:javascript
  var users_modal;

  $(document).ready(function(){
    users_modal = new ModalCRUD({

    });
  });
.row-fluid.non-print
  .span12.text-right
    %br
    = submit_tag("Find hopper", :class=>"btn btn-success", :onclick=>'search_user()' )

#container
  -if @user
    =render partial: 'hopper_info'

app/views/admin/hoppers/hopper_list.html.haml
= render partial: 'layouts/modal_crud'
:javascript
  var hops_modal;
  var zips_modal;

  $(document).ready(function(){
    hops_modal = new ModalCRUD({});
    zips_modal = new ModalCRUD({

    });
  });
.row-fluid
  .span12.text-right
    %br
    = submit_tag("Find hopper by hop", :class=>"btn btn-success", :onclick=>'search_hop()' )
    = submit_tag("Find hopper by zip", :class=>"btn btn-success", :onclick=>'search_zip()' )
    = submit_tag("Find all hoppers", :class=>"btn btn-success", :onclick=>'select_all()' )
#container
  -if @users
    =render partial: 'generate_hop_list'

app/views/admin/hoppers/winners_list.html.haml
- prizes =[]
.row-fluid
  .span12
    .grid
      =grid(@winners_grid, upper_pagination_panel: true) do |g|
        -g.column name:'Winners',  model: 'User', attribute: 'user_name' do |prize|
          -prize.user.user_name
        -g.column name:'Place', attribute: 'place'
        -g.column name:'Prize', attribute: 'cost'
        -g.column name:'Prize type', attribute: 'prize_type'
        -g.column name: 'Hop name', model: 'Hop',  attribute: 'name' do |prize|
          -link_to prize.hop.name, admin_hop_path(prize.hop) if prize.hop
        -g.column name: '' do |prize|
          -prizes << prize.id if prize
          -link_to 'email to user',  admin_messages_email_tool_path({:id=> [prize.user.id]}), class: 'btn btn-mini btn-success'
        -g.column name: '' do |prize|
          -link_to 'message to user', admin_messages_message_tool_path({:id=> [prize.user.id]}), class: 'btn btn-mini btn-success'

.row-fluid
  -if !prizes.blank?
    .span6.text-left
      =link_to 'Export to Excel', admin_hoppers_winners_to_excel_path({winners: prizes, :format => 'xls'}), class: 'btn btn-success'
    .span6.text-right
      =button_to 'Export to PDF', admin_hoppers_winners_to_pdf_path({winners: prizes, :format => 'pdf'}), class: 'btn btn-success' ,:target => '_blank'