config/routes.rb
  require 'will_paginate/array'
CashHoppers::Application.routes.draw do

  get "settings/get"

  get "settings/set"

  root :to => 'pages#home'
  get 'pages/hoppers_activity'
  get 'pages/business_level'
  get 'pages/terms'
  get 'pages/trade_show'
  get 'users/index'
  get 'pages/faq'

  namespace :admin do
    resources :asks

    get 'pages/index', :as => 'index'


    post "users/change_user_role"
    get "users/tasks_photo"
    get "users/index"
    post "users/unsubscribe_user"
    delete'users/delete_user/:id',              to:  'users#delete_user'

    resources :applications

    #hops
    resources :hops, only: [:create]
    get 'regular_hops',                    to: 'hops#regular'
    get 'daily_hops',                      to: 'hops#daily'
    get 'current_hops',                    to: 'hops#current'
    get 'archived_hops',                   to: 'hops#archived'
    get 'hop/:id',                         to: 'hops#show',              as: 'hop'
    get 'hops/new_regular',                to: 'hops#new_regular',       as: 'new_regular_hop'
    get 'hops/new_daily',                  to: 'hops#new_daily',         as: 'new_daily_hop'
    get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
    get 'hop/:id/edit_daily',              to: 'hops#edit_daily',        as: 'edit_daily_hop'
    delete 'hop/:id',                      to: 'hops#destroy',           as: 'hop'
    put 'hop/:id',                         to: 'hops#update',            as: 'hop'
    post 'close_hop/:id',                  to: 'hops#close',             as: 'close_hop'
    post 'hops/print_hop_to_pdf',          to: 'hops#print_hop_to_pdf',      as: 'print_hop_to_pdf'
    post 'hops/print_hop_list_to_pdf',     to: 'hops#print_hop_list_to_pdf',      as: 'print_hop_list_to_pdf'
    post 'hops/import_from_excel',         to: 'hops#import_from_excel',      as: 'import_from_excel'
    post 'hops/print_hop_to_excel',        to: 'hops#print_hop_to_excel',      as: 'print_hop_to_excel'
    post 'hops/print_hops_to_excel',       to: 'hops#print_hops_to_excel',      as: 'print_hops_to_excel'
    get 'hops/render_hoppers',            to: 'hops#render_hoppers',           as: 'render_hoppers'
    get 'hops/hop_photos',                to: 'hops#hop_photos',               as: 'hop_photos'
    get 'hops/export_photos_zip',         to: 'hops#export_photos_zip',        as: 'export_photos_zip'
    get 'hops/edit_photo',                to: 'hops#edit_photo',               as: 'edit_photo'
    post 'hops/delete_photo',                to: 'hops#delete_photo',           as: 'delete_photo'

    #hop_tasks
    resources :hop_tasks

    #prizes
    resources :prizes

    post 'prizes/random_user' ,             to: 'prizes#random_user' , as: 'random_user'
    post 'prizes/accept_user' ,             to: 'prizes#accept_user' , as: 'accept_user'
    #ads
    resources :ads

    match "hoppers/find_hopper"
    match "hoppers/hopper_list"
    match '/hoppers/search_hoppers' => "hoppers#search_hoppers"
    get '/hoppers/search_user'
    get '/hoppers/search_hop_list'
    get '/hoppers/search_zip_list'

    post '/hoppers/select_user'
    post '/hoppers/select_hop'
    post '/hoppers/select_zip'
    post '/hoppers/list_by_zip'
    post '/hoppers/list_by_hop'
    post '/hoppers/search_by_name' => 'hoppers#search_by_name'
    post '/hoppers/search_by_zip' => 'hoppers#search_by_zip'
    post '/hoppers/search_by_hop' => 'hoppers#search_by_hop'
    post '/hoppers/hopper_to_pdf' => 'hoppers#hopper_to_pdf'
    post '/hoppers/winners_to_pdf' => 'hoppers#winners_to_pdf'
    get '/hoppers/export_to_excel' => 'hoppers#export_to_excel'
    get '/hoppers/winners_to_excel' => 'hoppers#winners_to_excel'
    post '/hoppers/select_all' => 'hoppers#select_all'
    get '/hoppers/winners_list' => 'hoppers#winners_list'

    #messages
    get 'messages/email_tool'
    get 'messages/message_tool'
    post 'messages/message_create'
    post 'messages/email_create'
    get 'messages/hops_list'
    get 'messages/users_list'
    get 'messages/email_history'
    get 'messages/message_history'
    delete 'messages/destroy_message'
    post 'messages/get_user_list'


  end

  namespace :api do
    #session
    post 'sessions',                       to: 'sessions#create',        as: 'login'
    post 'sign_up',                        to: 'sessions#sign_up',       as: 'sign_up'
    delete 'sessions',                     to: 'sessions#destroy',       as: 'logout'
    post 'confirm_registration',           to: 'sessions#confirm_registration'
    post 'sign_in_via_service',            to: 'sessions#sign_in_via_service'
    get 'sessions/service_exist',          to: 'sessions#service_exist'
    post 'sessions/set_android_registration_id', to: 'sessions#set_android_registration_id'
    post 'sessions/reset_password',        to: 'sessions#reset_password'

    get 'ads/get_ads' => 'ads#index'

    #hops
    get 'hops/regular',                    to: 'hops#regular'
    get 'hops/daily',                      to: 'hops#daily'
    post 'hops/assign',                    to: 'hops#assign'
    get 'hop/get_tasks',                   to: 'hops#get_tasks'
    get 'hop/get_hop',                     to: 'hops#get_hop_by_id'
    get 'hop/score',                       to: 'hops#score'
    get 'hops/yesterdays_winner',          to: 'hops#yesterdays_winner'
    get 'hop/prizes',                      to: 'hops#prizes'
    post 'hop/disable_password',            to: 'hops#disable_password'
    get 'task/get_hop_task',               to: 'user_hop_tasks#get_hop_task_by_id'
    post 'payment/buy_hop',                to: 'payment#buy_hop'

    #users hop tasks
    post 'task/submit',                    to: 'user_hop_tasks#create'
    get 'tasks/get_friends_hop_tasks',     to: 'user_hop_tasks#friends_hop_tasks'
    get 'tasks/get_all_hoppers_hop_tasks', to: 'user_hop_tasks#all_hoppers_hop_tasks'
    post 'task/like',                      to: 'user_hop_tasks#like'
    get 'task/likes_count',                to: 'user_hop_tasks#likes_count'
    post 'task/comment',                   to: 'user_hop_tasks#comment'
    get 'task/get_comments',               to: 'user_hop_tasks#comments'
    post 'task/notify_by_share',           to: 'user_hop_tasks#notify_by_share'
    get 'task/get_user_hop_task_by_id',    to: 'user_hop_tasks#get_user_hop_task_by_id'

    #friends
    get 'friends/get_friends',             to: 'friends#get_friends'
    get 'friends/get_requested_friends',   to: 'friends#get_requested_friends'
    get 'friends/get_pending_friends',     to: 'friends#get_pending_friends'
    post 'friends/send_request',           to: 'friends#send_request'
    post 'friends/accept_request',         to: 'friends#accept_request'
    post 'friends/decline_request',        to: 'friends#decline_request'
    post 'friends/cancel_request',         to: 'friends#cancel_request'
    post 'friends/delete_friend',          to: 'friends#delete_friend'

    #messages
    post 'messages/send_message',          to: 'messages#send_message_to_friends'
    get 'messages/synchronize',            to: 'messages#synchronize_messages'
    get 'messages/thread',                 to: 'messages#get_users_messages_thread'
    get 'messages/history',                to: 'messages#messages_history'
    delete 'messages/remove_message',      to: 'messages#remove_message'

    #users

    get "users/index"
    get 'users/get_users',                 to: 'users#index'
    get 'users/get_my_info',               to: 'users#get_my_info'
    get 'users/get_user_info',             to: 'users#get_user_info'
    post 'users/update_profile',           to: 'users#update_profile'

    #events
    get 'notifications',                   to: 'notifications#get_events_list'

    #settings
    post 'settings/set',                   to: 'settings#set'
    get 'settings/get',                    to: 'settings#get'

    #payment
    get 'payment/get_frog_legs_count',     to: 'payment#get_frog_legs_count'
    post 'payment/refill_your_account',    to: 'payment#refill_your_account'
    post 'payment/disable_ads',            to: 'payment#disable_ads'

  end

  devise_for :users, :controllers => {:sessions =>'CustomDevise::Sessions'}

  get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
  get 'user/:id',                        to: 'users#profile',          as: 'user'


  match '/auth/:service/callback' => 'services#add_zip'
  get 'services/add_zip', :to => 'services#add_zip'
 
  resources :services, :only => [:index, :create, :destroy]
  resources :ad_types

  get 'friends', to: 'friends#friends'
  get 'find_friends', to: 'friends#find_friends'
  post 'friends/create_request', to: 'friends#create_request'
  post 'friends/cancel_request', to: 'friends#cancel_request'
  post 'friends/accept_request', to: 'friends#accept_request'
  post 'friends/decline_request', to: 'friends#decline_request'
  post 'friends/delete_friend', to: 'friends#delete_friend'


  get 'messages/friends_list'
  get 'messages/friend_messages'
  post 'messages/synchronize'
  post 'messages/send_message'
  post 'messages/find_friend'

  get '/auth/failure' => 'pages#home'
end

app/models/ask.rb
class Ask < ActiveRecord::Base
  attr_accessible :answer, :ask
end

app/controllers/admin/asks_controller.rb
class  Admin::AsksController < Admin::AdminController
  layout 'home_layout', only: :show
  authorize_resource
    def index
        @asks = Ask.paginate(page: params[:page], per_page:15 )
        if request.content_type == 'text'
          render partial: 'list'
        end
    end

    def new
        @ask = Ask.new
      render partial: 'form'
    end

    def create
      @ask = Ask.new(params[:ask])
      if @ask.save
        render text: 'ok'
      else
        render partial: 'form'
      end
    end

    def edit
      @ask = Ask.find(params[:id])
     render partial: 'form'
    end

    def update
      @ask = Ask.find(params[:id])
      if @ask.update_attributes(params[:ask])
        render text: 'ok'
      else
        render partial: 'form'
      end
    end

    def destroy
      @ask = Ask.find(params[:id])
      @ask.destroy
      render text: 'ok'
    end




end

app/views/admin/asks/_form.haml
- if @ask.errors.any?
  - @ask.errors.full_messages.each do |msg|
    .alert.alert-error
      %button.close{type: :button, 'data-dismiss' => 'alert'}
      = msg
= form_for([:admin, @ask]) do |f|

  %table.hops-form
    %tr
      %td
        %b
          Question:
      %td
        %b
          = f.text_field :ask, class: 'span12'
    %tr
      %td
        %b
          Answer:
      %td
        %b
          = f.text_area :answer,:rows=>4, class: 'span12'
    %tr
      %td{colspan: 2}
        = link_to 'Submit', '#', class: 'btn btn-info', onclick: 'asks_modal.submitForm({}); return false;'

app/views/admin/asks/_list.haml
= will_paginate @asks, renderer: BootstrapPagination::Rails
- if @asks.blank?
  List has no rows
-else
  %table.table.table-condensed
    %tr
      %th
        Question
      %th
        Answer
      - @asks.each do |ask|
        %tr
          %td
            %div{stule: 'max-width: 100%; word-wrap: break-word;'}
              =ask.ask

          %td{stule: 'width: 50px'}
            %div{stule: 'width: 50px; word-wrap: break-word;'}
              =ask.answer
          %td
          %td{style: 'text-align: right'}
            %button.btn.btn-info.btn-mini{onclick: 'asks_modal.editRecord({}, "Edit ask", "' + edit_admin_ask_path(ask) + '")'}
              Edit
            %button.btn.btn-danger.btn-mini{onclick: 'asks_modal.removeRecord("' + admin_ask_path(ask) + '", {})'}
              Delete
= will_paginate @asks, renderer: BootstrapPagination::Rails

app/views/admin/asks/edit.html.haml
%h1 Editing Question

= render 'form'

= link_to 'Show', admin_ask_path(@ask)
\|
= link_to 'Back', admin_asks_path

app/views/admin/asks/index.html.haml
- unless request.content_type == 'text'
  = render partial: 'layouts/modal_crud'
  :javascript
    var asks_modal;
    $(document).ready(function(){
      asks_modal = new ModalCRUD({
        new_path: "#{new_admin_ask_path}",
        index_path: "#{admin_asks_path}",
        list_id: 'asksTable'
      });
    });
  .row-fluid
    .span12.text-right
      %button.btn.btn-info{onclick: 'asks_modal.newRecord({jhj: "hj"}, "Create ask");'}
        New Question

#asksTable
  = render partial: 'list'

app/views/admin/asks/new.html.haml
%h1 New Question

= render 'form'

= link_to 'Back', admin_asks_path

app/views/admin/asks/show.html.haml
%link{'href' => "css/bootstrap.min.css", 'rel' => 'stylesheet', 'type' => 'text/css'}/
%link{'href' => "css/bootstrap-responsive.min.css", 'rel' => 'stylesheet', 'type' => 'text/css'}/
:css
  h3{

  }
.row-fluid{style: 'margin-top: 5%'}
  .span12.text-center
    -for i in @asks
      %h3
        =i.ask
      .text
        = i.answer

<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle collapsed" href="#viewpage" data-parent="#accordion-demo" data-toggle="collapse">

Test Your Page

</a></div><div id="viewpage" class="accordion-body in collapse" style="height: 0px;"><div class="accordion-inner"><form id="viewpage"><p>

Naturally, the last thing you'll want to do is test your
page with the accordion wizard. Once you've confirmed that
it's working as expected, release it on the world. Your
users will definitely appreciate the feedback and guidance
it gives to multi-step and complex tasks on your web site.

</p></form></div>
<!--/.accordion-inner -->
</div>
<!-- /#viewpage -->
</div>
<!-- /.accordion-group -->
</div>