config/routes.rb
  require 'will_paginate/array'
CashHoppers::Application.routes.draw do

  get "settings/get"

  get "settings/set"

  root :to => 'pages#home'
  get 'pages/hoppers_activity'
  get 'pages/business_level'
  get 'pages/terms'
  get 'pages/trade_show'
  get 'users/index'
  get 'pages/faq'

  namespace :admin do
    resources :asks

    get 'pages/index', :as => 'index'


    post "users/change_user_role"
    get "users/tasks_photo"
    get "users/index"
    post "users/unsubscribe_user"
    delete'users/delete_user/:id',              to:  'users#delete_user'

    resources :applications

    #hops
    resources :hops, only: [:create]
    get 'regular_hops',                    to: 'hops#regular'
    get 'daily_hops',                      to: 'hops#daily'
    get 'current_hops',                    to: 'hops#current'
    get 'archived_hops',                   to: 'hops#archived'
    get 'hop/:id',                         to: 'hops#show',              as: 'hop'
    get 'hops/new_regular',                to: 'hops#new_regular',       as: 'new_regular_hop'
    get 'hops/new_daily',                  to: 'hops#new_daily',         as: 'new_daily_hop'
    get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
    get 'hop/:id/edit_daily',              to: 'hops#edit_daily',        as: 'edit_daily_hop'
    delete 'hop/:id',                      to: 'hops#destroy',           as: 'hop'
    put 'hop/:id',                         to: 'hops#update',            as: 'hop'
    post 'close_hop/:id',                  to: 'hops#close',             as: 'close_hop'
    post 'hops/print_hop_to_pdf',          to: 'hops#print_hop_to_pdf',      as: 'print_hop_to_pdf'
    post 'hops/print_hop_list_to_pdf',     to: 'hops#print_hop_list_to_pdf',      as: 'print_hop_list_to_pdf'
    post 'hops/import_from_excel',         to: 'hops#import_from_excel',      as: 'import_from_excel'
    post 'hops/print_hop_to_excel',        to: 'hops#print_hop_to_excel',      as: 'print_hop_to_excel'
    post 'hops/print_hops_to_excel',       to: 'hops#print_hops_to_excel',      as: 'print_hops_to_excel'
    get 'hops/render_hoppers',            to: 'hops#render_hoppers',           as: 'render_hoppers'
    get 'hops/hop_photos',                to: 'hops#hop_photos',               as: 'hop_photos'
    get 'hops/export_photos_zip',         to: 'hops#export_photos_zip',        as: 'export_photos_zip'
    get 'hops/edit_photo',                to: 'hops#edit_photo',               as: 'edit_photo'
    post 'hops/delete_photo',                to: 'hops#delete_photo',           as: 'delete_photo'

    #hop_tasks
    resources :hop_tasks

    #prizes
    resources :prizes

    post 'prizes/random_user' ,             to: 'prizes#random_user' , as: 'random_user'
    post 'prizes/accept_user' ,             to: 'prizes#accept_user' , as: 'accept_user'
    #ads
    resources :ads

    match "hoppers/find_hopper"
    match "hoppers/hopper_list"
    match '/hoppers/search_hoppers' => "hoppers#search_hoppers"
    get '/hoppers/search_user'
    get '/hoppers/search_hop_list'
    get '/hoppers/search_zip_list'

    post '/hoppers/select_user'
    post '/hoppers/select_hop'
    post '/hoppers/select_zip'
    post '/hoppers/list_by_zip'
    post '/hoppers/list_by_hop'
    post '/hoppers/search_by_name' => 'hoppers#search_by_name'
    post '/hoppers/search_by_zip' => 'hoppers#search_by_zip'
    post '/hoppers/search_by_hop' => 'hoppers#search_by_hop'
    post '/hoppers/hopper_to_pdf' => 'hoppers#hopper_to_pdf'
    post '/hoppers/winners_to_pdf' => 'hoppers#winners_to_pdf'
    get '/hoppers/export_to_excel' => 'hoppers#export_to_excel'
    get '/hoppers/winners_to_excel' => 'hoppers#winners_to_excel'
    post '/hoppers/select_all' => 'hoppers#select_all'
    get '/hoppers/winners_list' => 'hoppers#winners_list'

    #messages
    get 'messages/email_tool'
    get 'messages/message_tool'
    post 'messages/message_create'
    post 'messages/email_create'
    get 'messages/hops_list'
    get 'messages/users_list'
    get 'messages/email_history'
    get 'messages/message_history'
    delete 'messages/destroy_message'
    post 'messages/get_user_list'


  end

  namespace :api do
    #session
    post 'sessions',                       to: 'sessions#create',        as: 'login'
    post 'sign_up',                        to: 'sessions#sign_up',       as: 'sign_up'
    delete 'sessions',                     to: 'sessions#destroy',       as: 'logout'
    post 'confirm_registration',           to: 'sessions#confirm_registration'
    post 'sign_in_via_service',            to: 'sessions#sign_in_via_service'
    get 'sessions/service_exist',          to: 'sessions#service_exist'
    post 'sessions/set_android_registration_id', to: 'sessions#set_android_registration_id'
    post 'sessions/reset_password',        to: 'sessions#reset_password'

    get 'ads/get_ads' => 'ads#index'

    #hops
    get 'hops/regular',                    to: 'hops#regular'
    get 'hops/daily',                      to: 'hops#daily'
    post 'hops/assign',                    to: 'hops#assign'
    get 'hop/get_tasks',                   to: 'hops#get_tasks'
    get 'hop/get_hop',                     to: 'hops#get_hop_by_id'
    get 'hop/score',                       to: 'hops#score'
    get 'hops/yesterdays_winner',          to: 'hops#yesterdays_winner'
    get 'hop/prizes',                      to: 'hops#prizes'
    post 'hop/disable_password',            to: 'hops#disable_password'
    get 'task/get_hop_task',               to: 'user_hop_tasks#get_hop_task_by_id'
    post 'payment/buy_hop',                to: 'payment#buy_hop'

    #users hop tasks
    post 'task/submit',                    to: 'user_hop_tasks#create'
    get 'tasks/get_friends_hop_tasks',     to: 'user_hop_tasks#friends_hop_tasks'
    get 'tasks/get_all_hoppers_hop_tasks', to: 'user_hop_tasks#all_hoppers_hop_tasks'
    post 'task/like',                      to: 'user_hop_tasks#like'
    get 'task/likes_count',                to: 'user_hop_tasks#likes_count'
    post 'task/comment',                   to: 'user_hop_tasks#comment'
    get 'task/get_comments',               to: 'user_hop_tasks#comments'
    post 'task/notify_by_share',           to: 'user_hop_tasks#notify_by_share'
    get 'task/get_user_hop_task_by_id',    to: 'user_hop_tasks#get_user_hop_task_by_id'

    #friends
    get 'friends/get_friends',             to: 'friends#get_friends'
    get 'friends/get_requested_friends',   to: 'friends#get_requested_friends'
    get 'friends/get_pending_friends',     to: 'friends#get_pending_friends'
    post 'friends/send_request',           to: 'friends#send_request'
    post 'friends/accept_request',         to: 'friends#accept_request'
    post 'friends/decline_request',        to: 'friends#decline_request'
    post 'friends/cancel_request',         to: 'friends#cancel_request'
    post 'friends/delete_friend',          to: 'friends#delete_friend'

    #messages
    post 'messages/send_message',          to: 'messages#send_message_to_friends'
    get 'messages/synchronize',            to: 'messages#synchronize_messages'
    get 'messages/thread',                 to: 'messages#get_users_messages_thread'
    get 'messages/history',                to: 'messages#messages_history'
    delete 'messages/remove_message',      to: 'messages#remove_message'

    #users

    get "users/index"
    get 'users/get_users',                 to: 'users#index'
    get 'users/get_my_info',               to: 'users#get_my_info'
    get 'users/get_user_info',             to: 'users#get_user_info'
    post 'users/update_profile',           to: 'users#update_profile'

    #events
    get 'notifications',                   to: 'notifications#get_events_list'

    #settings
    post 'settings/set',                   to: 'settings#set'
    get 'settings/get',                    to: 'settings#get'

    #payment
    get 'payment/get_frog_legs_count',     to: 'payment#get_frog_legs_count'
    post 'payment/refill_your_account',    to: 'payment#refill_your_account'
    post 'payment/disable_ads',            to: 'payment#disable_ads'

  end

  devise_for :users, :controllers => {:sessions =>'CustomDevise::Sessions'}

  get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
  get 'user/:id',                        to: 'users#profile',          as: 'user'


  match '/auth/:service/callback' => 'services#add_zip'
  get 'services/add_zip', :to => 'services#add_zip'
 
  resources :services, :only => [:index, :create, :destroy]
  resources :ad_types

  get 'friends', to: 'friends#friends'
  get 'find_friends', to: 'friends#find_friends'
  post 'friends/create_request', to: 'friends#create_request'
  post 'friends/cancel_request', to: 'friends#cancel_request'
  post 'friends/accept_request', to: 'friends#accept_request'
  post 'friends/decline_request', to: 'friends#decline_request'
  post 'friends/delete_friend', to: 'friends#delete_friend'


  get 'messages/friends_list'
  get 'messages/friend_messages'
  post 'messages/synchronize'
  post 'messages/send_message'
  post 'messages/find_friend'

  get '/auth/failure' => 'pages#home'
end

app/controllers/api/friends_controller.rb
class Api::FriendsController < Api::ApplicationController

  before_filter :load_friend, only: [:send_request, :accept_request, :decline_request, :cancel_request, :delete_friend]

  def get_friends
    @friends = @current_user.friends
    if @friends.length == 0
      bad_request ['You have no friends.'], 406
    else
      render 'get_friends', content_type: 'application/json'
    end

  end

  def get_requested_friends
    @requested_friends = @current_user.requested_friends
    if @requested_friends.length == 0
      bad_request ['You have no friends.'], 406
    else
      render 'get_requested_friends', content_type: 'application/json'
    end

  end

  def get_pending_friends
    @pending_friends = @current_user.pending_friends
    if @pending_friends.length == 0
      bad_request ['You have no friends.'], 406
    end

    render 'get_pending_friends', content_type: 'application/json'

  end

  def send_request
    Friendship.request(current_user, @friend)
    render :json => {success: true,
                     info: 'Friend request sent.',
                     status: 200
    }
  end

  def accept_request
    if @current_user.requested_friends.include?(@friend)
      Friendship.accept(@current_user, @friend)
      render :json => {success: true,
                       info: "Friendship with user #{@friend.id} accepted!",
                       status: 200
      }
    else
      bad_request ["No friendship request from user with id #{@friend.id}."], 406
    end
  end

  def decline_request
    if @current_user.requested_friends.include?(@friend)
      Friendship.breakup(@current_user, @friend)
      render :json => {success: true,
                       info: "Friendship with user #{@friend.id} declined!",
                       status: 200
      }
    else
      bad_request ["No friendship request from user with id #{@friend.id}."], 406
    end
  end

  def cancel_request
    if @current_user.pending_friends.include?(@friend)
      Friendship.breakup(@current_user, @friend)
      render :json => {success: true,
                       info: "Friendship request to user #{@friend.id} canceled!",
                       status: 200
      }
    else
      bad_request ["No request for friendship with #{@friend.id}"], 406
    end
  end

  def delete_friend
    if @current_user.friends.include?(@friend)
      Friendship.breakup(@current_user, @friend)
      render :json => {success: true,
                       info: "Friendship with user #{@friend.id} deleted!",
                       status: 200
      }
    else
      bad_request ["You aren't friends with #{@friend.id}"], 406
    end
  end

  private

  def load_friend
    @friend = User.where(:id => params[:friend_id]).first if params['friend_id']
    unless @friend
      bad_request ["Can't find user by id #{params['friend_id']}"], 406
    end
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_filter :setup_friends, except: [:find_friends, :friends]

  def friends
    params[:tab] = :friends
    @friends = current_user.friends
    @requested_friends = current_user.requested_friends
    @pending_friends = current_user.pending_friends
  end

  def find_friends
    params[:tab] = :find_friends

    conditions = {deleted: !true}
    unless params[:query].blank?
      conditions = ["(first_name LIKE ? OR last_name LIKE ? ) AND deleted != 1", "%#{params[:query]}%", "%#{params[:query]}%"]
    end

    @users = User.paginate(page: params[:page], per_page:10, conditions: conditions  )

    respond_to do |format|
      format.text do
        render partial: 'users_list'
      end
      format.html do
      end
    end
  end

  def sub_layout
    'friends/tabs'
  end

# Send a friend request.
# We'd rather call this "request", but that's not allowed by Rails.
  def create_request
    Friendship.request(@user, @friend)
    flash[:notice] = "Friend request sent."
    redirect_to :back
  end

  def accept_request
    if @user.requested_friends.include?(@friend)
      Friendship.accept(@user, @friend)
      flash[:notice] = "Friendship with #{@friend.first_name} accepted!"
    else
      flash[:notice] = "No friendship request from #{@friend.first_name}."
    end
    redirect_to :back
  end

  def decline_request
    if @user.requested_friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:notice] = "Friendship with #{@friend.first_name} declined"
    else
      flash[:notice] = "No friendship request from #{@friend.first_name}."
    end
    redirect_to :back
  end

  def cancel_request
    if @user.pending_friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:notice] = "Friendship request canceled."
    else
      flash[:notice] = "No request for friendship with #{@friend.first_name}"
    end
    redirect_to :back
  end

  def delete_friend
    if @user.friends.include?(@friend)
      Friendship.breakup(@user, @friend)
      flash[:notice] = "Friendship with #{@friend.first_name} deleted!"
    else
      flash[:notice] = "You aren't friends with #{@friend.first_name}"
    end
    redirect_to :back
  end

  private

  def setup_friends
    @user = current_user
    @friend = User.find(params[:id])
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
  # Return an appropriate friendship status message.
  def friendship_status(user, friend)
    friendship = Friendship.find_by_user_id_and_friend_id(user, friend)
    return "" if friendship.nil?
    case friendship.status
      when 'requested'
        "#{friend.first_name} would like to be your friend."
      when 'pending'
        "You have requested friendship from #{friend.first_name}."
      when 'accepted'
        "#{friend.first_name} is your friend."
    end
  end
end

app/views/friends/_tabs.haml
%ul.nav.nav-tabs.hoppers{style: 'margin-bottom: 0px'}
  %li{:class => ('active' if params[:tab] == :friends)}
    =link_to 'Friends', friends_path
  %li{:class => ('active' if params[:tab] == :find_friends)}
    = link_to 'Find', find_friends_path

= yield

app/views/friends/_users_list.haml
.span10.offset1
.row-fluid
  .span7
    = will_paginate @users, renderer: BootstrapPagination::Rails, inner_window: 0, outer_window: 0, :style=>'margin: 0px 0px;'
  .span5.text-center.row

    .input-append{style: 'font-size: 100%'}
      = text_field_tag :user, params[:query], class: '', id: 'search_field', :placeholder=> "Enter FIRST or LAST name"
      = link_to 'Find', find_friends_path, class: 'btn btn-success', id: 'search_button', :style =>'line-height: 20px; margin-left: -4px; font-size: 100%'
%table.table
  %tr
    %th
      First Name
    %th
      Last Name
    %th
  - @users.each do |user|
    -if user != current_user
      %tr
        %td
          = link_to user.first_name, user_path(:id => user.id)
        %td
          = user.last_name
        %td.field-button
          - if current_user && user != current_user
            = friendship_status current_user, user
            - unless Friendship.exists? current_user, user
              = link_to "Add to friends",
                friends_create_request_path(id: user.id),
                method: :post,
                confirm: "Send friend request to #{user.first_name}?",
                class: 'btn btn-mini btn-success'
= will_paginate @users, renderer: BootstrapPagination::Rails, inner_window: 0, outer_window: 0

app/views/friends/find_friends.haml
:css
  body {
      padding: 0%;
      /*display: none;*/

  }
  .span12.text-center{
      margin: 0;
  }
  fieldset.btn.profile{
   border-top: none;
    width: 80.1%;
  }
  .nav.nav-tabs.hoppers>li{

    margin-bottom: -4px;
  }


  @media(min-width:100px)and(max-width: 790px){

      fieldset.btn{
          /*display: none;*/
          border: none;
          padding: 0%;
          text-align: center;


          font-size: 100%;

      }
      .span6.text-center.small-screen{
        display: block;
        width: auto;

      }
      .span6.text-center.large-screen{
        display: none;


      }
      .span6.text-center{
        margin: 0px;
      }
       table tr td,table tr th{
         font-size: 80%;
       }
      table tr td div{
         width: 50px;
      }
      fieldset.btn.profile{
        width: 100%;
      }
      able tr td a.btn.btn-mini{
        display: none;
        width: 50px;
        font-size: 80%;
        height: 20px;
      }
  }

.span12.text-center
  %fieldset.btn.profile

    #users_list
      = render :partial => 'users_list'

app/views/friends/friends.haml
:css
  body {
      padding: 0%;
      /*display: none;*/

  }
  .span12.text-center{
      margin: 0;
  }
  fieldset.btn.profile{
    width: 82.9%;
  }
    fieldset.btn.profile{
     border-top: none;
      width: 80.1%;
    }
    .nav.nav-tabs.hoppers>li{

      margin-bottom: -4px;
    }

  @media(min-width:100px)and(max-width: 790px){

      fieldset.btn{
          /*display: none;*/
          border: none;
          padding: 0%;
          text-align: center;


          font-size: 100%;

      }
      .span6.text-center.small-screen{
        display: block;
        width: auto;

      }
      .span6.text-center.large-screen{
        display: none;


      }
      .span6.text-center{
        margin: 0px;
      }
       table tr td,table tr th{
         font-size: 80%;
       }
      table tr td div{
         width: 50px;
      }
       fieldset.btn.profile{
          width: 100%;
        }

  }

.span12.text-center
  %fieldset.btn.profile

    %h3
      = pluralize(current_user.friends.count, "friend")
    %table.table.table-condensed
      %tr
        %th
          First Name
        %th
          Last Name
        %th
        - @friends.each do |friend|
          %tr
            %td
              = link_to friend.first_name, user_path(friend)
            %td
              = friend.last_name
            %td.delete-button
              = link_to "Delete", friends_delete_friend_path(id: friend.id), confirm: "Really delete friendship with #{friend.first_name}?", method: :post, class: 'btn btn-mini btn-danger'
    %h3
      = pluralize(current_user.requested_friends.count, "requested friend")
    %table.table.table-condensed
      %tr
        %th
          First Name
        %th
          Last Name
        %th
        - @requested_friends.each do |requester|
          %tr
            %td
              = requester.first_name
            %td
              = requester.last_name
            %td.button.delete-button
              = link_to "Accept", friends_accept_request_path(id: requester.id), method: :post, class: 'btn btn-mini btn-success'
              = link_to "Decline", friends_decline_request_path(id: requester.id), confirm: "Really decline friendship with #{requester.first_name}?", method: :post, class: 'btn btn-mini btn-danger'
    %h3
      = pluralize(current_user.pending_friends.count, "pending friend")
    %table.table.table-condensed
      %tr
        %th
          First Name
        %th
          Last Name
        %th
        - @pending_friends.each do |friend|
          %tr
            %td
              = friend.first_name
            %td
              = friend.last_name
            %td.delete-button
              = link_to "Cancel",
                    friends_cancel_request_path(id: friend.id),
                    confirm: "Cancel friendship request?",
                    method: :post,
                    class: 'btn btn-mini btn-danger'