config/routes.rb
  require 'will_paginate/array'
CashHoppers::Application.routes.draw do

  get "settings/get"

  get "settings/set"

  root :to => 'pages#home'
  get 'pages/hoppers_activity'
  get 'pages/business_level'
  get 'pages/terms'
  get 'pages/trade_show'
  get 'users/index'
  get 'pages/faq'

  namespace :admin do
    resources :asks

    get 'pages/index', :as => 'index'


    post "users/change_user_role"
    get "users/tasks_photo"
    get "users/index"
    post "users/unsubscribe_user"
    delete'users/delete_user/:id',              to:  'users#delete_user'

    resources :applications

    #hops
    resources :hops, only: [:create]
    get 'regular_hops',                    to: 'hops#regular'
    get 'daily_hops',                      to: 'hops#daily'
    get 'current_hops',                    to: 'hops#current'
    get 'archived_hops',                   to: 'hops#archived'
    get 'hop/:id',                         to: 'hops#show',              as: 'hop'
    get 'hops/new_regular',                to: 'hops#new_regular',       as: 'new_regular_hop'
    get 'hops/new_daily',                  to: 'hops#new_daily',         as: 'new_daily_hop'
    get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
    get 'hop/:id/edit_daily',              to: 'hops#edit_daily',        as: 'edit_daily_hop'
    delete 'hop/:id',                      to: 'hops#destroy',           as: 'hop'
    put 'hop/:id',                         to: 'hops#update',            as: 'hop'
    post 'close_hop/:id',                  to: 'hops#close',             as: 'close_hop'
    post 'hops/print_hop_to_pdf',          to: 'hops#print_hop_to_pdf',      as: 'print_hop_to_pdf'
    post 'hops/print_hop_list_to_pdf',     to: 'hops#print_hop_list_to_pdf',      as: 'print_hop_list_to_pdf'
    post 'hops/import_from_excel',         to: 'hops#import_from_excel',      as: 'import_from_excel'
    post 'hops/print_hop_to_excel',        to: 'hops#print_hop_to_excel',      as: 'print_hop_to_excel'
    post 'hops/print_hops_to_excel',       to: 'hops#print_hops_to_excel',      as: 'print_hops_to_excel'
    get 'hops/render_hoppers',            to: 'hops#render_hoppers',           as: 'render_hoppers'
    get 'hops/hop_photos',                to: 'hops#hop_photos',               as: 'hop_photos'
    get 'hops/export_photos_zip',         to: 'hops#export_photos_zip',        as: 'export_photos_zip'
    get 'hops/edit_photo',                to: 'hops#edit_photo',               as: 'edit_photo'
    post 'hops/delete_photo',                to: 'hops#delete_photo',           as: 'delete_photo'

    #hop_tasks
    resources :hop_tasks

    #prizes
    resources :prizes

    post 'prizes/random_user' ,             to: 'prizes#random_user' , as: 'random_user'
    post 'prizes/accept_user' ,             to: 'prizes#accept_user' , as: 'accept_user'
    #ads
    resources :ads

    match "hoppers/find_hopper"
    match "hoppers/hopper_list"
    match '/hoppers/search_hoppers' => "hoppers#search_hoppers"
    get '/hoppers/search_user'
    get '/hoppers/search_hop_list'
    get '/hoppers/search_zip_list'

    post '/hoppers/select_user'
    post '/hoppers/select_hop'
    post '/hoppers/select_zip'
    post '/hoppers/list_by_zip'
    post '/hoppers/list_by_hop'
    post '/hoppers/search_by_name' => 'hoppers#search_by_name'
    post '/hoppers/search_by_zip' => 'hoppers#search_by_zip'
    post '/hoppers/search_by_hop' => 'hoppers#search_by_hop'
    post '/hoppers/hopper_to_pdf' => 'hoppers#hopper_to_pdf'
    post '/hoppers/winners_to_pdf' => 'hoppers#winners_to_pdf'
    get '/hoppers/export_to_excel' => 'hoppers#export_to_excel'
    get '/hoppers/winners_to_excel' => 'hoppers#winners_to_excel'
    post '/hoppers/select_all' => 'hoppers#select_all'
    get '/hoppers/winners_list' => 'hoppers#winners_list'

    #messages
    get 'messages/email_tool'
    get 'messages/message_tool'
    post 'messages/message_create'
    post 'messages/email_create'
    get 'messages/hops_list'
    get 'messages/users_list'
    get 'messages/email_history'
    get 'messages/message_history'
    delete 'messages/destroy_message'
    post 'messages/get_user_list'


  end

  namespace :api do
    #session
    post 'sessions',                       to: 'sessions#create',        as: 'login'
    post 'sign_up',                        to: 'sessions#sign_up',       as: 'sign_up'
    delete 'sessions',                     to: 'sessions#destroy',       as: 'logout'
    post 'confirm_registration',           to: 'sessions#confirm_registration'
    post 'sign_in_via_service',            to: 'sessions#sign_in_via_service'
    get 'sessions/service_exist',          to: 'sessions#service_exist'
    post 'sessions/set_android_registration_id', to: 'sessions#set_android_registration_id'
    post 'sessions/reset_password',        to: 'sessions#reset_password'

    get 'ads/get_ads' => 'ads#index'

    #hops
    get 'hops/regular',                    to: 'hops#regular'
    get 'hops/daily',                      to: 'hops#daily'
    post 'hops/assign',                    to: 'hops#assign'
    get 'hop/get_tasks',                   to: 'hops#get_tasks'
    get 'hop/get_hop',                     to: 'hops#get_hop_by_id'
    get 'hop/score',                       to: 'hops#score'
    get 'hops/yesterdays_winner',          to: 'hops#yesterdays_winner'
    get 'hop/prizes',                      to: 'hops#prizes'
    post 'hop/disable_password',            to: 'hops#disable_password'
    get 'task/get_hop_task',               to: 'user_hop_tasks#get_hop_task_by_id'
    post 'payment/buy_hop',                to: 'payment#buy_hop'

    #users hop tasks
    post 'task/submit',                    to: 'user_hop_tasks#create'
    get 'tasks/get_friends_hop_tasks',     to: 'user_hop_tasks#friends_hop_tasks'
    get 'tasks/get_all_hoppers_hop_tasks', to: 'user_hop_tasks#all_hoppers_hop_tasks'
    post 'task/like',                      to: 'user_hop_tasks#like'
    get 'task/likes_count',                to: 'user_hop_tasks#likes_count'
    post 'task/comment',                   to: 'user_hop_tasks#comment'
    get 'task/get_comments',               to: 'user_hop_tasks#comments'
    post 'task/notify_by_share',           to: 'user_hop_tasks#notify_by_share'
    get 'task/get_user_hop_task_by_id',    to: 'user_hop_tasks#get_user_hop_task_by_id'

    #friends
    get 'friends/get_friends',             to: 'friends#get_friends'
    get 'friends/get_requested_friends',   to: 'friends#get_requested_friends'
    get 'friends/get_pending_friends',     to: 'friends#get_pending_friends'
    post 'friends/send_request',           to: 'friends#send_request'
    post 'friends/accept_request',         to: 'friends#accept_request'
    post 'friends/decline_request',        to: 'friends#decline_request'
    post 'friends/cancel_request',         to: 'friends#cancel_request'
    post 'friends/delete_friend',          to: 'friends#delete_friend'

    #messages
    post 'messages/send_message',          to: 'messages#send_message_to_friends'
    get 'messages/synchronize',            to: 'messages#synchronize_messages'
    get 'messages/thread',                 to: 'messages#get_users_messages_thread'
    get 'messages/history',                to: 'messages#messages_history'
    delete 'messages/remove_message',      to: 'messages#remove_message'

    #users

    get "users/index"
    get 'users/get_users',                 to: 'users#index'
    get 'users/get_my_info',               to: 'users#get_my_info'
    get 'users/get_user_info',             to: 'users#get_user_info'
    post 'users/update_profile',           to: 'users#update_profile'

    #events
    get 'notifications',                   to: 'notifications#get_events_list'

    #settings
    post 'settings/set',                   to: 'settings#set'
    get 'settings/get',                    to: 'settings#get'

    #payment
    get 'payment/get_frog_legs_count',     to: 'payment#get_frog_legs_count'
    post 'payment/refill_your_account',    to: 'payment#refill_your_account'
    post 'payment/disable_ads',            to: 'payment#disable_ads'

  end

  devise_for :users, :controllers => {:sessions =>'CustomDevise::Sessions'}

  get 'hop/:id/edit_regular',            to: 'hops#edit_regular',      as: 'edit_regular_hop'
  get 'user/:id',                        to: 'users#profile',          as: 'user'


  match '/auth/:service/callback' => 'services#add_zip'
  get 'services/add_zip', :to => 'services#add_zip'
 
  resources :services, :only => [:index, :create, :destroy]
  resources :ad_types

  get 'friends', to: 'friends#friends'
  get 'find_friends', to: 'friends#find_friends'
  post 'friends/create_request', to: 'friends#create_request'
  post 'friends/cancel_request', to: 'friends#cancel_request'
  post 'friends/accept_request', to: 'friends#accept_request'
  post 'friends/decline_request', to: 'friends#decline_request'
  post 'friends/delete_friend', to: 'friends#delete_friend'


  get 'messages/friends_list'
  get 'messages/friend_messages'
  post 'messages/synchronize'
  post 'messages/send_message'
  post 'messages/find_friend'

  get '/auth/failure' => 'pages#home'
end

app/controllers/api/hops_controller.rb
class Api::HopsController < Api::ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :daily, :assign, :get_tasks, :disable_password]
  before_filter :load_hop, only: [:assign, :get_tasks, :get_hop_by_id, :score, :prizes]

  def regular
    params[:page] ||= 1
    params[:per_page] ||= 10

    hops = Hop.arel_table
    hop_tasks = HopTask.arel_table
    prizes = Prize.arel_table
    hoppers = User.arel_table
    hoppers_hops = HoppersHops.arel_table

    where_conditions = hops[:daily].eq(false)
                       .and(hops[:time_end].gteq(Time.now))
                       .and(hops[:close].eq(false))
                       .and(hop_tasks[:id].not_eq(nil))
                       .and(prizes[:id].not_eq(nil))
                       .and((hops[:zip].matches('%'+@current_user.zip+'%')).or(hops[:zip].eq(nil)).or(hops[:zip].eq('')))

    @hops = Hop
      .includes(:hop_tasks)
      .includes(:prizes)
      .includes(:hoppers)
      .select('hops.*')
      .where(where_conditions)
      .group('hops.id')
      .order("IF(hoppers_hops.user_id IS NULL , -1, hoppers_hops.user_id) != #{@current_user.id} , hops.created_at DESC")
      .limit(params[:per_page].to_i)
      .offset((params[:page].to_i - 1) * params[:per_page].to_i)

    if @hops.blank?
      bad_request(['Hops not found.'], 406)
    else
      render 'regular', content_type: 'application/json'
    end
  end

  def daily
    #.joins("LEFT OUTER JOIN `hoppers_hops` ON `hoppers_hops`.`hop_id` = `hops`.`id`")
    params[:page] ||= 1
    params[:per_page] ||= 10

    hops = Hop.arel_table
    hop_tasks = HopTask.arel_table
    prizes = Prize.arel_table
    hoppers = User.arel_table
    hoppers_hops = HoppersHops.arel_table

    where_conditions = hops[:daily].eq(true)
      .and(hops[:close].eq(false))
      .and(hop_tasks[:id].not_eq(nil))
      .and(prizes[:id].not_eq(nil))
      .and((hops[:zip].matches('%'+@current_user.zip+'%')).or(hops[:zip].eq(nil)).or(hops[:zip].eq('')))
      .and(hops[:time_start].in(DateTime.now.beginning_of_day..DateTime.now.end_of_day))

    @daily_hops = Hop
      .includes(:hop_tasks)
      .includes(:prizes)
      .includes(:hoppers)
      .select('hops.*')
      .where(where_conditions)
      .group('hops.id')
      .order("IF(hoppers_hops.user_id IS NULL , -1, hoppers_hops.user_id) != #{@current_user.id} , hops.created_at DESC")
      .limit(params[:per_page].to_i)
      .offset((params[:page].to_i - 1) * params[:per_page].to_i)

    if @daily_hops.blank?
      bad_request(['Daily hops not found.'], 406)
    else
      render 'daily', content_type: 'application/json'
    end
  end

  def get_tasks
    @hop_tasks = @hop.hop_tasks
    render 'get_tasks', content_type: 'application/json'
  end

  def get_hop_by_id
    render 'get_hop_by_id', content_type: 'application/json'
  end

  def score
    respond_to do |format|
      format.json{
        render :json => {success: true,
                         score: @hop.score(@current_user),
                         hoppers_count: @hop.hoppers.count,
                         rank: @hop.rank(@current_user),
                         status: 200
        }
      }
    end
  end

  def yesterdays_winner
    hop = Hop.get_daily_by_date DateTime.now - 1.day
    if hop
      prize = hop.prizes.order("place ASC").first
      if prize && prize.user_id
        respond_to do |format|
          format.json{
            render :json => {success: true,
                             winner_id: prize.user_id,
                             winners_first_name: prize.user.first_name,
                             winners_last_name: prize.user.last_name,
                             winners_avatar: prize.user.avatar.url,
                             score: prize.pts,
                             hoppers_count: hop.hoppers.count,
                             rank: prize.place,
                             hop_id: hop.id,
                             hop_name: hop.name,
                             cost: prize.cost,
                             status: 200
            }
          }
        end
      else
        bad_request(['Missing winner for yesterday\'s hop.'], 406)
      end
    else
      bad_request(['Missing yesterday\'s hop.'], 406)
    end
  end

  def prizes
    @prizes = @hop.prizes
    render 'prizes', content_type: 'application/json'
  end

  def disable_password
    @hop = Hop.find_by_id(params[:hop_id])
    if params[:password] == @hop.code
      @hop.disable_password @current_user
      respond_to do |format|
        format.json{
          render :json => {success: true,
            info: 'Password successfully disabled.',
            status: 200
          }
        }
      end
    else
      bad_request(['Wrong password.'], 200)
    end
  end

  private

  def load_hop
    @hop = Hop.where(:id => params[:hop_id]).first   #.includes(:hop_task).where("hop_tasks.id IS NOT NULL")
    bad_request(['Hop not found.'], 406) unless @hop
  end

end

app/controllers/hops_controller.rb
class HopsController < ApplicationController
  # GET /hops
  # GET /hops.json
  before_filter :authenticate_user!

  def index
    @hops = Hop.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @hops }
    end
  end

  # GET /hops/1
  # GET /hops/1.json
  def show

    @hop = Hop.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @hop }
    end
  end

  # GET /hops/new
  # GET /hops/new.json
  def new

    @hop = Hop.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @hop }
    end
  end

  # GET /hops/1/edit
  def edit
    @hop = Hop.find(params[:id])
  end

  # POST /hops
  # POST /hops.json
  def create
    params[:hop][:producer_id]=current_user.id
    @hop = Hop.new(params[:hop])

    respond_to do |format|
      if @hop.save
        format.html { redirect_to @hop, notice: 'Hop was successfully created.' }
        format.json { render json: @hop, status: :created, location: @hop }
      else
        format.html { render action: "new" }
        format.json { render json: @hop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hops/1
  # PUT /hops/1.json
  def update
    @hop = Hop.find(params[:id])

    respond_to do |format|
      if @hop.update_attributes(params[:hop])
        format.html { redirect_to @hop, notice: 'Hop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hops/1
  # DELETE /hops/1.json
  def destroy
    @hop = Hop.find(params[:id])
    @hop.destroy

    respond_to do |format|
      format.html { redirect_to hops_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/hops/_edit_photo.html.haml
.row-fluid
  .span3
    Hop task text
  .span3
    Hop task logo
  .span4.text-center
    Photo
  .span2
- if @photos
  -for i in @photos
    .row-fluid
      .span3
        = HopTask.find_by_id(i.hop_task_id).text
      .span3
        = image_tag HopTask.find_by_id(i.hop_task_id).logo, :size => "260x200"
      .span4
        = image_tag i.photo, :size => "260x200"
      .span2
        = button_to 'delete', admin_delete_photo_path({:id=>i.id, photos:  @photos_id, hop: @hop}) , :remote=> true , :class=>'btn btn-danger'

= link_to "Back", admin_hop_path(@hop)

app/views/admin/hops/_hops_list.haml
.grid
  = grid(@hops_grid, upper_pagination_panel: true) do |g|
    - g.blank_slate content_tag(:div, 'No records found')
    - g.column name: '', attribute: 'id', filter: false do |hop|
      - raw "<i #{((hop.hop_tasks.count == 0 || hop.prizes.count == 0 ) ? 'class="icon-warning-sign" style="color: red"' : '')}></i>"
      - raw "<i #{((hop.time_end < DateTime.now && !hop.close ) ? 'class=" icon-exclamation-sign" style="color: red"' : '')}></i>"

    - g.column name: 'Name', attribute: 'name', class: 'fix-long-div'
    - g.column name: 'Producer', attribute: 'user_name', model: User do |hop|
      - link_to(hop.producer.user_name, user_path(hop.producer)) if  hop.producer
    - g.column name: 'Price', attribute: 'price'
    - g.column name: 'Jackpot', attribute: 'jackpot'
    - g.column name: 'Hop photos' do |hop|
      - link_to 'photo', admin_hop_photos_path({:hop_id=>hop.id})

    - g.column name: 'Time Start', :attribute => 'time_start', filter: false do |hop|
      - hop.time_start.to_datetime.strftime(format='%Y-%m-%d %H:%M') + ' EST' if hop.time_start
    - unless @tab == 'daily_hops'
      - g.column name: 'Time End', :attribute => 'time_end', filter: false do |hop|
        - hop.time_end.to_datetime.strftime(format='%Y-%m-%d %H:%M') + ' EST' if hop.time_end
    - if @tab == 'current_hops' || @tab == 'archived_hops'
      - g.column name: 'Type', :attribute => 'daily',  filter: false do |hop|
        - hop.daily ? 'Daily': 'Regular'

    - g.column do |hop|
      - link_to('Show', admin_hop_path(hop), class: 'btn btn-mini')
    - if (User.producer?(current_user) || User.admin?(current_user))

      - g.column do |hop|

        -if User.can_edit?(current_user, hop.creator_id) && !(hop.close == true)
          - link_to('Edit', admin_edit_regular_hop_path(hop), class: 'btn btn-mini btn-info')

      - g.column do |hop|
        -if User.can_edit?(current_user, hop.creator_id) && !(hop.close == true)
          - link_to('Destroy', admin_hop_path(hop), method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' })
      - unless @tab == 'archived_hops'
        - g.column do |hop|
          -if User.can_edit?(current_user, hop.creator_id) && !(hop.close == true)
            - link_to('Close', admin_close_hop_path(hop), method: :post, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' })
      %br

app/views/admin/hops/daily.haml
- if User.producer?(current_user) || User.admin?(current_user)
  .text-right
    = link_to 'New daily hop', admin_new_daily_hop_path, class: 'btn btn-info'
%br
= render partial: 'hops_list'

app/views/admin/hops/hop_photos.html.haml
-#%h1{style: 'margin_top: 50px'}
-#  photos ---------------------
-#%p{style: 'margin_top: 50px'}
-#= @hop_task_photo.each do |i|
-#  i.
-#%h1{style: 'margin_top: 50px'}
-#  photos ---------------------
-#%p{style: 'margin_top: 50px'}
-#= @hop_task_photo.inspect
-if !@hop_task_photo.blank?
  .photo-backgraund
    .carousel.slide#hopPhotos
      .carousel-inner.text-center
        .item.active
          =image_tag @hop_task_photo.first.photo.url

        - @hop_task_photo.each do |task|
          .item

            =image_tag task.photo.url

      %a.carousel-control.left{"data-slide" => "prev", :href => "#hopPhotos"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#hopPhotos"} ›
    .row-fluid.banner
      .span5.text-right#logo{:style=> ' max-height: 100px'}
        = image_tag @hop.logo.url , :style=> 'max-width: 100%; max-height: 100px'
      .span7#text
        =@hop.name
        %br
        =@hop.time_start.to_datetime.strftime(format='%Y-%m-%d %H:%M') + ' EST'
-else
  .text{:style=>'position: absolute; top: 40%; left: 40%'}
    .alert-error
      %h3
        NO PHOTOS

%br
%br
- if current_user && !@hop_task_photo.blank?
  .row-fluid
    .span4
    .span4.text-center
      =link_to 'My page', user_path(current_user.id)
    .span4

  -unless User.user?(current_user)
    -unless @hop_task_photo.blank?
      .row-fluid
        .span4
        .span4.text-center
          =link_to 'Manage photo',  admin_edit_photo_path({:id =>@hop_task_photo}), :class => 'btn btn-success'
        .span4
      %br
      .row-fluid
        .span4
        .span4.text-center
          =link_to 'Download photos as zip',  admin_export_photos_zip_path({:id =>@hop_task_photo}), :class => 'btn btn-success'
        .span4

app/views/admin/hops/show.haml
= render partial: 'layouts/modal_crud'
:javascript
  var tasks_modal;
  var ads_modal;
  var prizes_modal;
  var hoppers_modal;

  $(document).ready(function(){
    tasks_modal = new ModalCRUD({
      new_path: "#{new_admin_hop_task_path}",
      index_path: "#{admin_hop_tasks_path}",
      list_id: 'tasksTable'
    });
    hoppers_modal = new ModalCRUD({
      index_path: "#{admin_hop_tasks_path}",
      list_id: 'hoppersTable'
    });
    ads_modal = new ModalCRUD({
      new_path: "#{new_admin_ad_path}",
      index_path: "#{admin_ads_path}",
      list_id: 'adsTable'
    });
    prizes_modal = new ModalCRUD({
      new_path: "#{new_admin_prize_path}",
      index_path: "#{admin_prizes_path({:hop_id=> @hop.id})}",
      list_id: 'prizesTable'
    });
  });
- if @hop.hop_tasks.count == 0
  .alert.alert-error
    Hop must have at least one task!
- if @hop.prizes.count == 0
  .alert.alert-error
    Hop must have at least one prize place!
%h2
  .row-fluid
    .text-left.span8{style: 'max-width: 63%;word-wrap: break-word;'}
      Hop:
      = @hop.name
    .text-right.span4
      - if @hop.daily
        = link_to 'Back', admin_daily_hops_path, class: 'btn btn-info'
      - else
        = link_to 'Back', admin_regular_hops_path, class: 'btn btn-info'
      - if (User.producer?(current_user) || User.admin?(current_user)) && User.can_edit?(current_user,@hop.creator_id) && !(@hop.close == true)
        = link_to('Edit', admin_edit_regular_hop_path(@hop), class: 'btn btn-success')
        = link_to('Destroy', admin_hop_path(@hop), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' })

%br


.row-fluid
  .span6


    = image_tag @hop.logo.url, class: 'img-polaroid', style: 'max-width: 100%; max-height: 400px'
  .span6
    %table.hops-form
      %tr
        %td
          %b
            Name:
        %td
          .fix-long-div
            = @hop.name
      %tr
        %td
          %b
            Zip:
        %td
          = @hop.zip
      %tr
        %td
          %b
            Link:
        %td
          = @hop.link

      %tr
        %td
          %b
            Time start:
        %td

          = @hop.time_start.to_datetime.strftime(format='%Y-%m-%d %H:%M') + ' EST'



      - unless @hop.daily
        %tr
          %td
            %b
              Time end:
          %td
            = @hop.time_end.to_datetime.strftime(format='%Y-%m-%d %H:%M') + ' EST'
        %tr
          %td
            %b
              Producer:
          %td
            - if @hop.producer
              .fix-long-div
                = @hop.producer.first_name
                = @hop.producer.last_name
        %tr
          %td
            %b
              Producer contact:
          %td
            - if @hop.producer
              = @hop.producer.contact
        %tr
          %td
            %b
              Producer Phone:
          %td
            - if @hop.producer
              = @hop.producer.phone
        %tr
          %td
            %b
              Producer Email:
          %td
            - if @hop.producer
              .fix-long-div
                = @hop.producer.email
        %tr
          %td
            %b
              Code:
          %td
            = @hop.code
        %tr
          %td
            %b
              Price:
          %td
            = @hop.price
        %tr
          %td
            %b
              Jackpot:
          %td
            -if @hop.jackpot.to_s.match(/(\$)|[a-zA-Z]/).nil? && !@hop.jackpot.blank?
              = number_to_currency(@hop.jackpot )
            -else
              =@hop.jackpot
        %tr
          %td
            %b
              Special event:
          %td
            = @hop.event
%hr

.row-fluid
  .span6
    %h4
      Prizes:
  .span6.text-right
    - if User.producer?(current_user) || User.admin?(current_user) && !(@hop.close == true)
      %button.btn.btn-success{onclick: 'prizes_modal.newRecord({hop_id: ' + @hop.id.to_s + '}, "Create prize");'}
        New Prize
.accept_user
#prizesTable
  = render partial: 'admin/prizes/list'

%hr
.row-fluid
  .span6
    %h4
      Tasks:
  .span6.text-right
    - if (User.producer?(current_user) || User.admin?(current_user) || User.sponsor?(current_user)) && !(@hop.close == true)
      %button.btn.btn-success{onclick: 'tasks_modal.newRecord({hop_id: ' + @hop.id.to_s + '}, "Create hop task");'}
        New Hop Task
#tasksTable
  = render partial: 'admin/hop_tasks/tasks'

%hr
.row-fluid
  .span6
    %h4
      Ads:
  .span6.text-right
    - if !(@hop.close == true)

      %button.btn.btn-success{onclick: 'ads_modal.newRecord({hop_id: ' + @hop.id.to_s + '}, "Create ad");'}
        New Ad
#adsTable
  = render partial: 'admin/ads/list'

%hr
-#=  @hop.creator_id
-#= current_user.id
-#= User.can_edit?(current_user, @hop.creator_id)
%h4
  Hoppers:
-#- user = User.find_by_email('viktor.danch@gmail.com')
-#= UserHopTask.create(:hop_task_id => @hop.hop_tasks[0].id, :user_id => user.id, :photo =>user.avatar, :comment=>'comment'  )
-#=@hop.hoppers << user
- if @hoppers.blank?
  List has no rows
- else
  #hoppersTable
    = render partial: 'hopper_list'


%br
.row-fluid
  .span2.text-left
    = link_to 'Export to Pdf',  admin_print_hop_to_pdf_path(:id => @hop.id,  :format => 'pdf'),:method => 'post',:target=>"_blank", :class => 'btn btn-success'
    %br
    %br
      -if User.can_edit?(current_user,@hop.creator_id)&& !@hop.close == true
        = link_to('Close', admin_close_hop_path(@hop), method: :post, class: 'btn btn-danger', data: { confirm: 'Are you sure?' })
  .span10
    .text-right
      = link_to 'Export to Excel',  admin_print_hop_to_excel_path(:id => @hop.id, :format => 'xls' ),:method => 'post', :class => 'btn btn-success'